version: 2

models:
  - name: users
    description: "Mock users table"
    columns:
      - name: id
        description: "Primary key"
      - name: full_name
        description: "Customer's full name"
        tags: [PII, sensitive]
      - name: email
        description: "Customer's email address"
        tags: [PII]
      - name: phone_number
        description: "Customer's phone number"
        tags: [PII]
      - name: dob
        description: "Date of birth"
        tags: [PII, sensitive]

  - name: transactions
    description: "Mock transactions table"
    columns:
      - name: transaction_id
      - name: user_id
      - name: amount
      - name: ip_address
        tags: [PII]

  - name: logs
    description: "Mock event logs"
    columns:
      - name: timestamp
      - name: user_id
      - name: event_type
      - name: page_url

  - name: marketing_emails
    description: "Marketing email list"
    columns:
      - name: email
        tags: [PII]
      - name: open_rate
      - name: unsubscribe_date

